name: expense_manager
description: An expense manager project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  currency_picker:
    path: 'packages/currency_picker'

  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10
  firebase_crashlytics: ^2.8.2
  firebase_auth: ^3.3.20
  permission_handler: ^10.0.1
  google_sign_in: ^5.4.2
  contacts_service: ^0.6.3
  firebase_storage: ^10.3.1
  cloud_firestore: ^3.2.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.1
  dio: ^4.0.6
  device_info_plus: ^4.1.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  meta: ^1.7.0
  pinput: ^2.2.12
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 900
        - asset: assets/fonts/poppins_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_regular.ttf
          weight: 300
        - asset: assets/fonts/poppins_light.ttf
          weight: 100


